### ISSUE TITLE
IntroMessage not working since new login system

### ISSUE THREAD

**Issue by NiktoutRO** [MrAntares/roBrowserLegacy-plugins#1]
From Alison:

go to:
roBrowserLegacy\src\Plugins\IntroMessage\IntroMessage.js

if your packetver is < 2018, set:
var WinLogin    = require('UI/Components/WinLogin/WinLogin/WinLogin');

if not:
var WinLogin    = require('UI/Components/WinLogin/WinLoginV2/WinLoginV2');

at this moment server is not set yet so its not possible to know the ui version

![image](https://github.com/MrAntares/roBrowserLegacy-plugins/assets/214579/216faed6-5262-477b-abec-b155f814f378)

**Comment by MrAntares** [comment]
Fixed in https://github.com/MrAntares/roBrowserLegacy-plugins/commit/542e2389f04149d65ac96de74a5eeab86341c773
